# dbt Cloud CLI does not use a profiles.yml file.
# We need one for sqlfluff to run the dbt templater in CI,
# which utilizes dbt-core internally.

snowflake:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      database: demo
      warehouse: demo
      schema: airflow
      threads: 8